# -*- coding: utf-8 -*-
"""Curated, ORIGINAL knowledge base for deterministic MCAT question generation.

Every fact and prebuilt question below is written fresh for this project and is
not copied from AAMC or any other copyrighted source.
"""

SECTION_MAP = {
    "Biology": "Biological & Biochemical Foundations",
    "Biochemistry": "Biological & Biochemical Foundations",
    "General Chemistry": "Chemical & Physical Foundations",
    "Organic Chemistry": "Chemical & Physical Foundations",
    "Physics": "Chemical & Physical Foundations",
    "Psychology": "Psychological, Social, & Biological Foundations",
    "Sociology": "Psychological, Social, & Biological Foundations",
    "Critical Analysis and Reasoning Skills (CARS)": "Critical Analysis and Reasoning Skills",
}

# Fact entries: feed the deterministic templates (recall / except / roman / sequence).
FACTS = [
    {
        "id": "cell-theory",
        "subject": "Biology",
        "topic": "The Cell",
        "kp": "1.1 Cell Theory",
        "term": "cell theory",
        "definition": "all living organisms are composed of cells, and the cell is the basic structural and functional unit of life",
        "true": [
            "All cells arise from pre-existing cells.",
            "Cells are the smallest units capable of carrying out life processes.",
            "Viruses are acellular and are therefore not classified as living organisms.",
        ],
        "false": [
            "The cell theory states that cells arise through spontaneous generation.",
            "All cells contain a membrane-bound nucleus.",
            "Only multicellular organisms are composed of cells.",
            "The mitochondrion is the basic unit of life.",
        ],
        "explanation": "The cell theory has three tenets: (1) all living things are made of cells; (2) the cell is the basic unit of life; and (3) all cells arise from pre-existing cells.",
        "templates": ["recall", "except", "roman"],
    },
    {
        "id": "nucleoside",
        "subject": "Biology",
        "topic": "The Cell",
        "kp": "1.2 Eukaryotic Cells",
        "term": "nucleoside",
        "definition": "a molecule composed of a nitrogenous base bonded to a five-carbon (pentose) sugar, without any phosphate group",
        "true": [
            "Adding one or more phosphate groups to a nucleoside converts it into a nucleotide.",
            "The sugar in a DNA nucleoside is deoxyribose.",
            "Nucleosides lack the phosphate groups found in nucleotides.",
        ],
        "false": [
            "A nucleoside contains a nitrogenous base, a sugar, and a phosphate group.",
            "The sugar component of a nucleoside is a six-carbon hexose.",
            "Nucleosides are found only in RNA and never in DNA.",
            "Nucleosides are the subunits that form the sugar-phosphate backbone directly.",
        ],
        "explanation": "A nucleoside is a nitrogenous base linked to a pentose sugar. Adding one or more phosphate groups converts it into a nucleotide, the subunit of nucleic acids.",
        "templates": ["recall", "except"],
    },
    {
        "id": "dna-helix",
        "subject": "Biology",
        "topic": "The Cell",
        "kp": "1.2 Eukaryotic Cells",
        "term": "DNA double helix",
        "definition": "two antiparallel strands of nucleotides held together by hydrogen bonds between complementary purine-pyrimidine base pairs",
        "true": [
            "Adenine pairs with thymine via two hydrogen bonds.",
            "Cytosine pairs with guanine via three hydrogen bonds.",
            "The sugar-phosphate backbone lies on the exterior of the helix.",
        ],
        "false": [
            "Adenine pairs with guanine via three hydrogen bonds.",
            "The two strands of the helix run in the same 5' to 3' direction.",
            "Uracil replaces thymine in the DNA double helix.",
            "The two strands are linked by covalent peptide bonds.",
        ],
        "explanation": "DNA is a double helix of two antiparallel strands. Adenine pairs with thymine (two hydrogen bonds) and cytosine with guanine (three hydrogen bonds); the sugar-phosphate backbone is on the outside.",
        "templates": ["recall", "except", "roman"],
    },
    {
        "id": "transcription",
        "subject": "Biology",
        "topic": "The Cell",
        "kp": "1.4 Genetics and Growth of Prokaryotic Cells",
        "term": "transcription",
        "definition": "the synthesis of a single-stranded messenger RNA (mRNA) molecule complementary to a DNA template strand",
        "true": [
            "RNA polymerase reads the template strand in the 3' to 5' direction.",
            "mRNA is synthesized in the 5' to 3' direction.",
            "Uracil is incorporated into mRNA in place of thymine.",
        ],
        "false": [
            "Transcription produces a double-stranded DNA copy of a gene.",
            "RNA polymerase requires a primer to initiate transcription.",
            "mRNA is synthesized in the 3' to 5' direction.",
            "Transcription is another name for translation.",
        ],
        "explanation": "Transcription copies a gene into single-stranded mRNA using RNA polymerase. The enzyme reads the template 3' to 5' and builds mRNA 5' to 3', using uracil in place of thymine.",
        "templates": ["recall", "except", "roman"],
    },
    {
        "id": "dna-polymerase",
        "subject": "Biology",
        "topic": "The Cell",
        "kp": "1.4 Genetics and Growth of Prokaryotic Cells",
        "term": "DNA polymerase",
        "definition": "the enzyme that synthesizes new DNA by adding nucleotides to the 3' hydroxyl end of a growing strand",
        "true": [
            "It reads the template strand in the 3' to 5' direction.",
            "It requires a primer with a free 3' hydroxyl group.",
            "It has proofreading (3' to 5' exonuclease) activity.",
        ],
        "false": [
            "It can initiate synthesis of a new strand without a primer.",
            "It synthesizes DNA in the 3' to 5' direction.",
            "It synthesizes the RNA primers used during replication.",
            "It adds nucleotides to the 5' end of the growing strand.",
        ],
        "explanation": "DNA polymerase extends a DNA strand in the 5' to 3' direction from an existing 3' hydroxyl group, reads the template 3' to 5', and proofreads via its 3' to 5' exonuclease activity.",
        "templates": ["recall", "except", "roman"],
    },
    {
        "id": "telomerase",
        "subject": "Biology",
        "topic": "The Cell",
        "kp": "1.4 Genetics and Growth of Prokaryotic Cells",
        "term": "telomerase",
        "definition": "a ribonucleoprotein enzyme that extends the telomeres at the ends of linear chromosomes",
        "true": [
            "It counteracts the progressive shortening of chromosomes during replication.",
            "It carries an RNA template complementary to the telomeric repeat sequence.",
            "It is highly active in germ cells and stem cells but low in most somatic cells.",
        ],
        "false": [
            "It shortens telomeres with each round of replication.",
            "It uses a DNA template to extend chromosome ends.",
            "It is a DNA polymerase that replicates the leading strand.",
            "Its activity is highest in fully differentiated somatic cells.",
        ],
        "explanation": "Telomerase adds repetitive sequences to telomeres using an internal RNA template, compensating for the end-replication problem that would otherwise shorten chromosomes each cycle.",
        "templates": ["recall", "except"],
    },
    {
        "id": "central-dogma",
        "subject": "Biology",
        "topic": "The Cell",
        "kp": "1.4 Genetics and Growth of Prokaryotic Cells",
        "term": "central dogma",
        "definition": "genetic information flows from DNA to RNA to protein",
        "process": "the flow of genetic information",
        "sequence": [
            "DNA replication",
            "transcription (DNA to mRNA)",
            "RNA processing",
            "translation (mRNA to protein)",
        ],
        "true": [
            "Transcription produces an RNA copy of a DNA sequence.",
            "Translation decodes an mRNA sequence into a polypeptide.",
        ],
        "false": [
            "Proteins are reverse-transcribed back into DNA in normal cells.",
            "Translation occurs before transcription in the flow of information.",
            "RNA is used as the permanent storage molecule for genetic information.",
        ],
        "explanation": "The central dogma describes the flow of genetic information: DNA is replicated, transcribed into RNA, and translated into protein. RNA does not serve as the permanent genetic storage molecule.",
        "templates": ["recall", "sequence"],
    },
    {
        "id": "cell-cycle",
        "subject": "Biology",
        "topic": "Reproduction",
        "kp": "2.1 The Cell Cycle and Mitosis",
        "term": "cell cycle",
        "definition": "the ordered series of events by which a cell grows, duplicates its DNA, and divides",
        "process": "the phases of the eukaryotic cell cycle",
        "sequence": [
            "G1 phase (growth)",
            "S phase (DNA synthesis)",
            "G2 phase (growth and preparation)",
            "M phase (mitosis and cytokinesis)",
        ],
        "true": [
            "DNA is duplicated during S phase.",
            "Chromosome segregation and cell division occur during M phase.",
        ],
        "false": [
            "DNA replication occurs during G1 phase.",
            "The cell divides before it duplicates its DNA.",
            "M phase occurs before S phase.",
        ],
        "explanation": "The cell cycle proceeds G1 -> S -> G2 -> M. DNA is synthesized in S phase, and the duplicated chromosomes are segregated and the cell divides during M phase.",
        "templates": ["recall", "sequence"],
    },
]

# Fully-authored questions that are too nuanced for the fact templates
# (vignettes, data interpretation, yes/no-reasoning, and comparison).
PREBUILT = [
    {
        "id": "gen-vignette-telomerase",
        "subject": "Biology",
        "topic": "The Cell",
        "knowledge_point": "1.4 Genetics and Growth of Prokaryotic Cells",
        "type": "discrete",
        "skill": "skill2",
        "subtype": "vignette",
        "question": "A researcher deletes the gene encoding telomerase in a cultured line of rapidly dividing cancer cells. Compared with untreated cells, the treated cells are most likely to exhibit:",
        "options": [
            "progressive shortening of chromosome ends over successive divisions",
            "lengthening of telomeres after each round of replication",
            "an increase in the rate of ribosomal RNA transcription",
            "no change in chromosome length over successive divisions",
        ],
        "correct": 0,
        "explanation": "Telomerase maintains telomere length. Without it, the end-replication problem causes telomeres to shorten with each cell division.",
    },
    {
        "id": "gen-vignette-nonsense",
        "subject": "Biology",
        "topic": "The Cell",
        "knowledge_point": "1.4 Genetics and Growth of Prokaryotic Cells",
        "type": "discrete",
        "skill": "skill1",
        "subtype": "vignette",
        "question": "A single nucleotide substitution in a protein-coding gene changes a glutamic acid codon (GAG) into a stop codon (UAG). This change is best classified as a:",
        "options": [
            "nonsense mutation",
            "missense mutation",
            "silent mutation",
            "frameshift mutation",
        ],
        "correct": 0,
        "explanation": "A substitution that creates a premature stop codon is a nonsense mutation, which typically truncates and inactivates the protein.",
    },
    {
        "id": "gen-data-gc-tm",
        "subject": "Biology",
        "topic": "The Cell",
        "knowledge_point": "1.2 Eukaryotic Cells",
        "type": "discrete",
        "skill": "skill4",
        "subtype": "data-interp",
        "question": "The melting temperature (Tm) of double-stranded DNA increases as the proportion of G-C base pairs increases. Three DNA samples contain 20%, 35%, and 50% G-C content. Which sample has the highest Tm?",
        "options": [
            "The sample with 50% G-C content",
            "The sample with 20% G-C content",
            "The sample with 35% G-C content",
            "All three samples have the same Tm",
        ],
        "correct": 0,
        "explanation": "G-C pairs form three hydrogen bonds (versus two for A-T), so greater G-C content increases the energy required to separate the strands, raising the melting temperature.",
    },
    {
        "id": "gen-data-cell-cycle",
        "subject": "Biology",
        "topic": "Reproduction",
        "knowledge_point": "2.1 The Cell Cycle and Mitosis",
        "type": "discrete",
        "skill": "skill4",
        "subtype": "data-interp",
        "question": "Flow cytometry measures the DNA content per cell in a population of dividing cells. At which phase of the cell cycle does the DNA content per cell double?",
        "options": [
            "S phase",
            "G1 phase",
            "G2 phase",
            "M phase",
        ],
        "correct": 0,
        "explanation": "DNA is replicated during S phase, so the DNA content per cell doubles between G1 and G2.",
    },
    {
        "id": "gen-yesno-telomerase",
        "subject": "Biology",
        "topic": "The Cell",
        "knowledge_point": "1.4 Genetics and Growth of Prokaryotic Cells",
        "type": "discrete",
        "skill": "skill2",
        "subtype": "yes-no",
        "question": "Is it accurate to state that telomerase uses an RNA template to extend chromosome ends?",
        "options": [
            "Yes, because telomerase contains an RNA template complementary to the telomeric repeat",
            "Yes, because telomerase carries a DNA template that guides elongation",
            "No, because telomerase consists only of protein subunits",
            "No, because telomerase does not catalyze DNA synthesis",
        ],
        "correct": 0,
        "explanation": "Telomerase is a ribonucleoprotein whose RNA component serves as the template for the DNA repeats it adds to telomeres.",
    },
    {
        "id": "gen-compare-nucleoside",
        "subject": "Biology",
        "topic": "The Cell",
        "knowledge_point": "1.2 Eukaryotic Cells",
        "type": "discrete",
        "skill": "skill1",
        "subtype": "compare",
        "question": "Which statement correctly distinguishes a nucleoside from a nucleotide?",
        "options": [
            "A nucleotide contains one or more phosphate groups, whereas a nucleoside does not",
            "A nucleoside contains phosphate groups, whereas a nucleotide does not",
            "A nucleotide contains a hexose sugar, whereas a nucleoside contains a pentose",
            "A nucleoside and a nucleotide differ only in their nitrogenous base",
        ],
        "correct": 0,
        "explanation": "A nucleotide is a nucleoside with one or more phosphate groups added; a nucleoside is only a nitrogenous base plus a pentose sugar.",
    },
]
